# Generated by Django 3.1.2 on 2020-10-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='alias',
            field=models.CharField(default='somerandom', max_length=10, unique=True),
        ),
    ]
