# Generated by Django 3.1.2 on 2020-10-26 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20201026_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='urls',
        ),
        migrations.AddField(
            model_name='url',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to=settings.AUTH_USER_MODEL),
        ),
    ]
